# Create user
POST http://0.0.0.0:8080/users
Content-Type: application/json

{
  "username": "john",
  "password": "secret"
}

# Get user
GET http://0.0.0.0:8080/users/1


# Invalid routes
GET http://0.0.0.0:8080/users
GET http://0.0.0.0:8080/users/
GET http://0.0.0.0:8080/users/0
GET http://0.0.0.0:8080/users/yolo
GET http://0.0.0.0:8080/users/9999999999999999999
POST http://0.0.0.0:8080/users
POST http://0.0.0.0:8080/users/0
POST http://0.0.0.0:8080/users/1
